openapi: "3.0.0"
info:
  title: Chotuve API Reference
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                      type: string
                  avatar:          # <-- image embedded into JSON
                    type: string
                    format: byte
                    description: Base64-encoded contents of the avatar image
  /users:
    get:
      summary: List all Users
      responses:
        '200':
          description: List all Users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        date_created:
          type: string
        date_updated:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        contact:
          type: string

       