openapi: "3.0.0"
info:
  title: Chotuve API Reference
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping
      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                      type: string
                  avatar:          # <-- image embedded into JSON
                    type: string
                    format: byte
                    description: Base64-encoded contents of the avatar image
  /users:
    get:
      summary: List all Users
      responses:
        '200':
          description: Users List
          content:
            application/json:
              schema:
                type: array
