openapi: "3.0.0"
info:
  title: Chotuve API Reference
  version: 1.0.0
servers:
  - url: https://fiuba-taller-2-media-server.herokuapp.com/
    description: Media Server
paths:
  /list:
    get:
      summary: List Videos
      tags:
        - videos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  videos:
                    type: array
                    items:
                      $ref: "#/components/schemas/Video"
components:
  schemas:
    Video:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        dateCreated:
          type: string
        size:
          type: string
        type:
          type: string
        url:
          type: string

  
