openapi: "3.0.0"
info:
  title: Chotuve API Reference
  version: 1.0.0
servers:
  - url: https://fiuba-taller-2-media-server.herokuapp.com/
    description: Media Server
paths:
  /list:
    get:
      summary: List Videos
      tags:
        - videos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  videoName:
                    $ref: "#/components/schemas/Video"
  /status:
    get:
      summary: Get server health
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /ping:
    get:
      summary: Ping server
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Ping received!"

components:
  schemas:
    Status:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
        data:
          $ref: '#/components/schemas/Health'

    Health:
      type: object
      properties:
        server_status:
          type: string
        database_status:
          type: string

    Video:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        dateCreated:
          type: string
        size:
          type: string
        type:
          type: string
        url:
          type: string
        thumb:
          type: string
