openapi: "3.0.0"
info:
  title: Chotuve API Reference
  version: 1.0.0
servers:
  - url: https://fiuba-taller-2-media-server.herokuapp.com/
    description: Media Server
paths:
  /list:
    get:
      deprecated: true
      summary: List Videos
      tags:
        - videos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  videoName:
                    $ref: "#/components/schemas/OutputVideo"
  /status:
    get:
      summary: Get server health
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /ping:
    get:
      summary: Ping server
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Ping received!"
  /videos:
    get:
      summary: Obtiene todos los videos
      description: Este endpoint además ofrece un filtro q para obtener videos con el id pasado como parámetro
      parameters:
        - in: query
          name: id
          required: false
          schema:
            type: string
          description: El id del video a obtener
      tags:
        - videos
      responses:
        '200':
          description: A paged array of videos
          content:
            application/json:
              schema:
                type: object
                properties:
                  videos:
                    type: array
                    items:
                      $ref: '#/components/schemas/OutputVideo'
    post:
      summary: Agrega un nuevo video
      tags:
        - videos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputVideo'
      responses:
        '201':
          description: Video recently added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputVideo'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputVideo'

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OutputVideo'



components:
  schemas:
    Status:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
        data:
          $ref: '#/components/schemas/Health'

    Health:
      type: object
      properties:
        server_status:
          type: string
        database_status:
          type: string

    InputVideo:
      type: object
      properties:
        video_id:
          type: string
        name:
          type: string
        date_created:
          type: string
        size:
          type: string
        type:
          type: string

    OutputVideo:
      type: object
      properties:
        video_id:
          type: string
        name:
          type: string
        dateCreated:
          type: string
        size:
          type: string
        type:
          type: string
        url:
          type: string
        thumb:
          type: string

    Error:
      type: object
      properties:
        error:
          type: string
